version: "3"
services:
  redis:
    image: "redis"
    restart: unless-stopped
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  node-app:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ACCESSTOKEN_SECRET_KEY=nVdai1506
      - ACCESSTOKEN_EXPIRES_IN=1d
      - MONGODB_URI=mongodb+srv://ochimot:Vandai1506@cluster0.bhpjcf9.mongodb.net/onlineShop
      - WEBPUSH_PUBLIC_KEY=BGA6DWy9kcp3ExfMLsRJX4XdfqU89KZenuIJy9zShBNFzb2B2aBRlFUOGLgRatB5T9xCRbGQYsUboERR7oZj1xY
      - WEBPUSH_PRIVATE_KEY=6LA-TnI2PMQ9FLUMyWsIeGt5PEJfgTFEYCwfwGnfHLA
