name: Deploy to Linux Server and Trigger Docker Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code to server
        run: scp -r . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/ec2-user

      - name: SSH into server and trigger Docker build
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /home/ec2-user && docker-compose up -d'
